---
- hosts: workstations
  vars:
    rvm1_rubies:
      - 'ruby-2.1.3'
    rvm1_install_flags: '--auto-dotfiles --user-install'
    rvm1_install_path: '/home/keelerm/.rvm'
    rvm1_user: 'keelerm'
  vars_files:
    - vars/mysql.yml


  roles:
    - { role: account-management, tags: ['account'] }
    - { role: cli-tools, tags: ['cli'] }
    - { role: languages, tags: ['languages'] }
    - { role: rvm_io.rvm1-ruby, tags: ['languages'], sudo_user: keelerm, sudo: true }
    - { role: servers, tags: ['servers', 'mysql'], }
    - { role: bennojoy.mysql,
        mysql_root_db_pass: "{{ mysql_root_pass }}",
        mysql_db: [],
        mysql_service: mariadb,
        mysql_users: [],
        mysql_bind_address: "localhost",
        tags: ['mysql']
      }

  tasks:
    - name: reset rvm
      command: rvm reset
      sudo_user: keelerm
      sudo: true
      tags: ['languages']
