---
- hosts: workstations
  vars:
    rvm1_rubies:
      - 'ruby-2.1.3'
    rvm1_install_flags: '--auto-dotfiles --user-install'
    rvm1_install_path: '/home/keelerm/.rvm'
    rvm1_user: 'keelerm'

  roles:
    - { role: account-management, tags: ['account'] }
    - { role: cli-tools, tags: ['cli'] }
    - { role: languages, tags: ['languages'] }
    - { role: rvm_io.rvm1-ruby, tags: ['languages'], sudo_user: keelerm, sudo: true }

  tasks:
    - name: reset rvm
      command: rvm reset
      sudo_user: keelerm
      sudo: true
      tags: ['languages']
