- name: download powerline fonts for {{ user }}
  git: repo=https://github.com/powerline/fonts dest={{ home }}/.powerline-fonts update=yes
  sudo_user: "{{ user }}"
  sudo: yes

- name: install powerline fonts for {{ user }}
  command: ./install.sh
  args:
      chdir: "{{ home }}/.powerline-fonts"
  sudo_user: "{{ user }}"
  sudo: yes
