---
# tasks file for desktop-apps
- include: google-chrome.yml
- include: fonts.yml

- name: install various desktop applications
  yum: name={{ item }} state=present
  with_items:
    - gimp
    - inkscape
    - dia
    - pencil
    - gnome-tweak-tool

- name: focus should follow the mouse
  command: gsettings set org.gnome.desktop.wm.preferences focus-mode 'mouse'
  sudo_user: keelerm
  sudo: yes