---
# tasks file for cli-tools
- name: install git
  yum: name=git state=present

- name: install tmux
  yum: name=tmux state=present

- name: install zsh
  yum: name=zsh state=present

- { include: emacs.yml, home: /home/keelerm/, user: keelerm }
- { include: emacs.yml, home: /root/, user: root }

- { include: dotfiles.yml, home: /home/keelerm/, user: keelerm }
- { include: vim.yml, home: /home/keelerm/, user: keelerm }

- { include: dotfiles.yml, home: /root, user: root }
- { include: vim.yml, home: /root/, user: root }

- { include: ssh.yml, home: /home/keelerm/, user: keelerm }
- { include: ssh.yml, home: /root/, user: root }