---
# tasks file for cli-tools
- name: install git
  yum: name=git state=present

- name: install hg
  yum: name=hg state=present

- name: install tmux
  yum: name=tmux state=present

- name: install zsh
  yum: name=zsh state=present

- name: install sqlite-devel
  yum: name=sqlite-devel state=present

- name: install python-markdown2
  yum: name=python-markdown2 state=present

- name: install ack
  yum: name=ack state=present

- name: install ag
  yum: name=the_silver_searcher state=present

- name: install nmap
  yum: name=nmap state=present

- name: install weechat
  yum: name=weechat state=present

- name: install youtube-dl
  yum: name=youtube-dl state=present

- { include: emacs.yml, home: /home/keelerm/, user: keelerm }
- { include: emacs.yml, home: /root/, user: root }

- { include: dotfiles.yml, home: /home/keelerm/, user: keelerm }
- { include: vim.yml, home: /home/keelerm/, user: keelerm }

- { include: dotfiles.yml, home: /root, user: root }
- { include: vim.yml, home: /root/, user: root }

- { include: ssh.yml, home: /home/keelerm/, user: keelerm }
- { include: ssh.yml, home: /root/, user: root }

- { include: exercism.yml, home: /home/keelerm/, user: keelerm }
