- name: install vim
  dnf: name=vim-enhanced state=present

- name: install ctags
  dnf: name=ctags state=present

- name: create .vim/bundle directory for {{ user }}
  file: path={{ home }}/.vim/bundle owner={{ user }} group={{ user }} state=directory
  sudo_user: "{{ user }}"
  sudo: yes

- name: install vundle for {{ user }}
  git: repo=git://github.com/gmarik/Vundle.vim dest={{ home }}/.vim/bundle/vundle
  sudo_user: "{{ user }}"
  sudo: yes

- name: copy over vim installation file for {{ user }}
  copy: src=bundle-install.vimrc dest={{ home }}/bundle-install.vimrc owner={{ user }} group={{ user }}
  sudo_user: "{{ user }}"
  sudo: yes

- name: install vim bundles for {{ user }}
  command: vim -u {{ home }}/bundle-install.vimrc +BundleInstall! +qall
  sudo_user: "{{ user }}"
  sudo: yes

- name: remove vim installation file for {{ user }}
  file: path="{{ home }}/bundle-install.vimrc" state=absent
