- name: install texlive
  yum: name=texlive state=present

- name: install texlive-minted
  yum: name=texlive-minted state=present

- name: install texliv-wrapfig
  yum: name=texlive-wrapfig state=present

- name: install texliv-ulem
  yum: name=texlive-ulem state=present
