---
# tasks file for languages
- name: create directories to store all projects
  file: path=/home/keelerm/Projects/{{ item }} owner=keelerm group=keelerm mode=700 state=directory
  with_items:
    - c
    - clojure
    - csharp
    - elisp
    - golang
    - java
    - latex
    - nodejs
    - php
    - python
    - ruby

- include: c++.yml
- include: clojure.yml
- include: csharp.yml
- include: golang.yml
- include: latex.yml
- include: nvm.yml
- include: php.yml
- include: python.yml
