- name: install nvm
  shell: curl https://raw.githubusercontent.com/creationix/nvm/v0.21.0/install.sh | bash
  sudo_user: keelerm
  sudo: yes
  args:
    creates: /home/keelerm/.nvm

- name: install stable node version
  shell: source /home/keelerm/.nvm/nvm.sh && nvm install stable
  sudo_user: keelerm
  sudo: yes

- name: make stable version default
  shell: source /home/keelerm/.nvm/nvm.sh && nvm alias default stable
  sudo_user: keelerm
  sudo: yes
