- name: create the log directory
  file: path=/var/log/ owner=root group=root mode=755 state=directory

- name: create the mysql log file
  file: path=/var/log/mysql.log owner=mysql group=mysql mode=755 state=touch